In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
Data1_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/matches.csv')
Data2_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/deliveries.csv')

In [ ]:

print("\033[1m Matches Dataset\033[1m")
Data1_df.info()
print("\n")
print("\033[1m Deliveries Dataset\033[1m")
Data2_df.info()

 Matches Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB


 Deliveries Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [ ]:
Data1_df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [ ]:
#Drop columns
Data1_df.drop(columns=['match_type', 'player_of_match', 'target_runs', 'target_overs',
                'super_over', 'umpire1', 'umpire2', 'season', 'city', 'date',
                'toss_winner', 'toss_decision', 'result_margin', 'result', 'method',
                'team1', 'team2'], inplace=True)

In [ ]:
#check Null Data
Data1_null = Data1_df.isnull().sum()
print(Data1_null)

id        0
venue     0
winner    5
dtype: int64

In [ ]:
Data1_df.fillna({'winner':'super_over'},inplace=True)
null_counts = Data1_df.isnull().sum()
print(null_counts)

id        0
venue     0
winner    0
dtype: int64

In [ ]:
Data2_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [ ]:
#Drop columns
Data2_df.drop(columns=['batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs', 'extras_type', 'player_dismissed','fielder','dismissal_kind'], inplace=True)
Data2_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,1,0
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,1,0
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,0
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0,0

In [ ]:
#check Null Data
Data2_null = Data2_df.isnull().sum()
print(Data2_null)

match_id        0
inning          0
batting_team    0
bowling_team    0
over            0
ball            0
total_runs      0
is_wicket       0
dtype: int64

In [ ]:
team_name_mapping = {
    'Kings XI Punjab': 'Punjab Kings',
    'Delhi Daredevils': 'Delhi Capitals',
    'Chennai Super Kings': 'CSK',
    'Royal Challengers Bangalore': 'RCB',
    'Royal Challengers Bengaluru': 'RCB',
    'Kolkata Knight Riders': 'Knight Riders',
    'Rajasthan Royals': 'RR',
    'Rising Pune Supergiants': 'Rising Pune Supergiants',
    'Rising Pune Supergiant': 'Rising Pune Supergiants',
    'Mumbai Indians': 'MI',
    'Deccan Chargers': 'Deccan Chargers',
    'Kochi Tuskers Kerala': 'Kochi Tuskers Kerala',
    'Pune Warriors': 'Pune Warriors',
    'Sunrisers Hyderabad': 'Sunrisers',
    'Gujarat Lions': 'Gujarat Lions',
    'Gujarat Titans': 'Gujarat Titans',
    'Lucknow Super Giants': 'Lucknow Super Giants',
    'super_over' : 'super_over'
}

Data1_df['winner']=Data1_df['winner'].replace(team_name_mapping)
Data2_df['batting_team']=Data2_df['batting_team'].replace(team_name_mapping)
Data2_df['bowling_team']=Data2_df['bowling_team'].replace(team_name_mapping)

In [ ]:
Data1_df.head()

       id                                       venue          winner
0  335982                       M Chinnaswamy Stadium   Knight Riders
1  335983  Punjab Cricket Association Stadium, Mohali             CSK
2  335984                            Feroz Shah Kotla  Delhi Capitals
3  335985                            Wankhede Stadium             RCB
4  335986                                Eden Gardens   Knight Riders

In [ ]:
Data2_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket
0,335982,1,Knight Riders,RCB,0,1,1,0
1,335982,1,Knight Riders,RCB,0,2,0,0
2,335982,1,Knight Riders,RCB,0,3,1,0
3,335982,1,Knight Riders,RCB,0,4,0,0
4,335982,1,Knight Riders,RCB,0,5,0,0

In [ ]:
# Check unique team names after mapping
print("Team names in 'winner':", Data1_df['winner'].unique())
print("Team names in 'batting_team':", Data2_df['batting_team'].unique())
print("Team names in 'bowling_team':", Data2_df['bowling_team'].unique())

Team names in 'winner': ['Knight Riders' 'CSK' 'Delhi Capitals' 'RCB' 'RR' 'Punjab Kings'
 'Deccan Chargers' 'MI' 'Pune Warriors' 'Kochi Tuskers Kerala'
 'super_over' 'Sunrisers' 'Rising Pune Supergiants' 'Gujarat Lions'
 'Gujarat Titans' 'Lucknow Super Giants']
Team names in 'batting_team': ['Knight Riders' 'RCB' 'CSK' 'Punjab Kings' 'RR' 'Delhi Capitals' 'MI'
 'Deccan Chargers' 'Kochi Tuskers Kerala' 'Pune Warriors' 'Sunrisers'
 'Rising Pune Supergiants' 'Gujarat Lions' 'Lucknow Super Giants'
 'Gujarat Titans']
Team names in 'bowling_team': ['RCB' 'Knight Riders' 'Punjab Kings' 'CSK' 'Delhi Capitals' 'RR' 'MI'
 'Deccan Chargers' 'Kochi Tuskers Kerala' 'Pune Warriors' 'Sunrisers'
 'Rising Pune Supergiants' 'Gujarat Lions' 'Gujarat Titans'
 'Lucknow Super Giants']

In [ ]:
venue_mapping = {
    "M Chinnaswamy Stadium": "M Chinnaswamy Stadium",
    "M.Chinnaswamy Stadium": "M Chinnaswamy Stadium",
    "M Chinnaswamy Stadium, Bengaluru": "M Chinnaswamy Stadium",

    "Punjab Cricket Association Stadium, Mohali": "Punjab Cricket Association Stadium, Mohali",
    "Punjab Cricket Association IS Bindra Stadium, Mohali": "Punjab Cricket Association Stadium, Mohali",
    "Punjab Cricket Association IS Bindra Stadium": "Punjab Cricket Association Stadium, Mohali",
    "Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh": "Punjab Cricket Association Stadium, Mohali",

    "Wankhede Stadium": "Wankhede Stadium",
    "Wankhede Stadium, Mumbai": "Wankhede Stadium",

    "Eden Gardens": "Eden Gardens",
    "Eden Gardens, Kolkata": "Eden Gardens",

    "Sawai Mansingh Stadium": "Sawai Mansingh Stadium",
    "Sawai Mansingh Stadium, Jaipur": "Sawai Mansingh Stadium",

    "Rajiv Gandhi International Stadium, Uppal": "Rajiv Gandhi International Stadium, Hyderabad",
    "Rajiv Gandhi International Stadium, Uppal, Hyderabad": "Rajiv Gandhi International Stadium, Hyderabad",
    "Rajiv Gandhi International Stadium": "Rajiv Gandhi International Stadium, Hyderabad",

    "MA Chidambaram Stadium, Chepauk": "MA Chidambaram Stadium, Chepauk",
    "MA Chidambaram Stadium, Chepauk, Chennai": "MA Chidambaram Stadium, Chepauk",
    "MA Chidambaram Stadium": "MA Chidambaram Stadium, Chepauk",

    "Dr DY Patil Sports Academy": "Dr DY Patil Sports Academy",
    "Dr DY Patil Sports Academy, Mumbai": "Dr DY Patil Sports Academy",

    "Brabourne Stadium": "Brabourne Stadium",
    "Brabourne Stadium, Mumbai": "Brabourne Stadium",

    "Himachal Pradesh Cricket Association Stadium": "Himachal Pradesh Cricket Association Stadium",
    "Himachal Pradesh Cricket Association Stadium, Dharamsala": "Himachal Pradesh Cricket Association Stadium",

    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium",
    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam": "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium",

    "Subrata Roy Sahara Stadium": "Subrata Roy Sahara Stadium",

    "Maharashtra Cricket Association Stadium": "Maharashtra Cricket Association Stadium",
    "Maharashtra Cricket Association Stadium, Pune": "Maharashtra Cricket Association Stadium",


    "Arun Jaitley Stadium": "Arun Jaitley Stadium, Delhi",
    "Arun Jaitley Stadium, Delhi": "Arun Jaitley Stadium, Delhi",
    "Feroz Shah Kotla":"Arun Jaitley Stadium, Delhi",

}
Data1_df['venue']=Data1_df['venue'].replace(venue_mapping)

Data1_df.head()

       id                                       venue          winner
0  335982                       M Chinnaswamy Stadium   Knight Riders
1  335983  Punjab Cricket Association Stadium, Mohali             CSK
2  335984                 Arun Jaitley Stadium, Delhi  Delhi Capitals
3  335985                            Wankhede Stadium             RCB
4  335986                                Eden Gardens   Knight Riders

In [ ]:
# Check if there are any unmapped teams
print("Unmapped Columns:\n")
winners_team = Data1_df[~Data1_df['winner'].isin(team_name_mapping.values())]
batting_team = Data2_df[~Data2_df['batting_team'].isin(team_name_mapping.values())]
bowling_team = Data2_df[~Data2_df['bowling_team'].isin(team_name_mapping.values())]
venues_data = Data1_df[~Data1_df['venue'].isin(Data1_df['venue'].unique())]

print("Unmapped winners:", winners_team['winner'].unique())
print("Unmapped batting teams:", batting_team['batting_team'].unique())
print("Unmapped bowling teams:", bowling_team['bowling_team'].unique())
print("Unmapped venues:", venues_data['venue'].unique())

Unmapped Columns:

Unmapped winners: []
Unmapped batting teams: []
Unmapped bowling teams: []
Unmapped venues: []

In [ ]:
print("Data 1: ",Data1_df.columns)
print("Data 2: ",Data2_df.columns)

Data 1:  Index(['id', 'venue', 'winner'], dtype='object')
Data 2:  Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'total_runs', 'is_wicket'],
      dtype='object')

In [ ]:
# Merged Both Data1 and Data2
merged_data = pd.merge(Data2_df, Data1_df, left_on='match_id', right_on='id', how='left')
print("Merged Data (Deliveries Data & Matches Data)\n")

Merged Data (Deliveries Data & Matches Data)

In [ ]:
merged_data = merged_data.drop(columns=['id'])
merged_data.head()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,venue,winner
0,335982,1,Knight Riders,RCB,0,1,1,0,M Chinnaswamy Stadium,Knight Riders
1,335982,1,Knight Riders,RCB,0,2,0,0,M Chinnaswamy Stadium,Knight Riders
2,335982,1,Knight Riders,RCB,0,3,1,0,M Chinnaswamy Stadium,Knight Riders
3,335982,1,Knight Riders,RCB,0,4,0,0,M Chinnaswamy Stadium,Knight Riders
4,335982,1,Knight Riders,RCB,0,5,0,0,M Chinnaswamy Stadium,Knight Riders

In [ ]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   match_id      260920 non-null  int64
 1   inning        260920 non-null  int64
 2   batting_team  260920 non-null  object
 3   bowling_team  260920 non-null  object
 4   over          260920 non-null  int64
 5   ball          260920 non-null  int64
 6   total_runs    260920 non-null  int64
 7   is_wicket     260920 non-null  int64
 8   venue         260920 non-null  object
 9   winner        260920 non-null  object
dtypes: int64(6), object(4)
memory usage: 19.9+ MB

In [ ]:
#Nul Counts Merged Data
null = merged_data.isnull().sum()
print(null)

match_id        0
inning          0
batting_team    0
bowling_team    0
over            0
ball            0
total_runs      0
is_wicket       0
venue           0
winner          0
dtype: int64

In [ ]:
# Cumulative Runs
merged_data["cumulative_runs"] = merged_data.groupby(['match_id','inning'])['total_runs'].cumsum()
print(merged_data)

        match_id  inning   batting_team bowling_team  over  ball  total_runs  \
0         335982       1  Knight Riders          RCB     0     1           1
1         335982       1  Knight Riders          RCB     0     2           0
2         335982       1  Knight Riders          RCB     0     3           1
3         335982       1  Knight Riders          RCB     0     4           0
4         335982       1  Knight Riders          RCB     0     5           0
...          ...     ...            ...          ...   ...   ...         ...
260915   1426312       2  Knight Riders    Sunrisers     9     5           1
260916   1426312       2  Knight Riders    Sunrisers     9     6           1
260917   1426312       2  Knight Riders    Sunrisers    10     1           1
260918   1426312       2  Knight Riders    Sunrisers    10     2           1
260919   1426312       2  Knight Riders    Sunrisers    10     3           1

        is_wicket                            venue         winner  \
0               0            M Chinnaswamy Stadium  Knight Riders
1               0            M Chinnaswamy Stadium  Knight Riders
2               0            M Chinnaswamy Stadium  Knight Riders
3               0            M Chinnaswamy Stadium  Knight Riders
4               0            M Chinnaswamy Stadium  Knight Riders
...           ...                              ...            ...
260915          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260916          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260917          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260918          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260919          0  MA Chidambaram Stadium, Chepauk  Knight Riders

        cumulative_runs
0                     1
1                     1
2                     2
3                     2
4                     2
...                 ...
260915              110
260916              111
260917              112
260918              113
260919              114

[260920 rows x 11 columns]

In [ ]:
# Overs Completed

merged_data["overs_completed"] =  merged_data['over'] + (merged_data['ball'] - 1) / 6

print(merged_data)

        match_id  inning   batting_team bowling_team  over  ball  total_runs  \
0         335982       1  Knight Riders          RCB     0     1           1
1         335982       1  Knight Riders          RCB     0     2           0
2         335982       1  Knight Riders          RCB     0     3           1
3         335982       1  Knight Riders          RCB     0     4           0
4         335982       1  Knight Riders          RCB     0     5           0
...          ...     ...            ...          ...   ...   ...         ...
260915   1426312       2  Knight Riders    Sunrisers     9     5           1
260916   1426312       2  Knight Riders    Sunrisers     9     6           1
260917   1426312       2  Knight Riders    Sunrisers    10     1           1
260918   1426312       2  Knight Riders    Sunrisers    10     2           1
260919   1426312       2  Knight Riders    Sunrisers    10     3           1

        is_wicket                            venue         winner  \
0               0            M Chinnaswamy Stadium  Knight Riders
1               0            M Chinnaswamy Stadium  Knight Riders
2               0            M Chinnaswamy Stadium  Knight Riders
3               0            M Chinnaswamy Stadium  Knight Riders
4               0            M Chinnaswamy Stadium  Knight Riders
...           ...                              ...            ...
260915          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260916          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260917          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260918          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260919          0  MA Chidambaram Stadium, Chepauk  Knight Riders

        cumulative_runs  overs_completed
0                     1         0.000000
1                     1         0.166667
2                     2         0.333333
3                     2         0.500000
4                     2         0.666667
...                 ...              ...
260915              110         9.666667
260916              111         9.833333
260917              112        10.000000
260918              113        10.166667
260919              114        10.333333

[260920 rows x 12 columns]

In [ ]:
#Cumulative Wickets

merged_data["cumulative_wickets"] = merged_data.groupby(['match_id','inning'])['is_wicket'].cumsum()
print(merged_data)

        match_id  inning   batting_team bowling_team  over  ball  total_runs  \
0         335982       1  Knight Riders          RCB     0     1           1
1         335982       1  Knight Riders          RCB     0     2           0
2         335982       1  Knight Riders          RCB     0     3           1
3         335982       1  Knight Riders          RCB     0     4           0
4         335982       1  Knight Riders          RCB     0     5           0
...          ...     ...            ...          ...   ...   ...         ...
260915   1426312       2  Knight Riders    Sunrisers     9     5           1
260916   1426312       2  Knight Riders    Sunrisers     9     6           1
260917   1426312       2  Knight Riders    Sunrisers    10     1           1
260918   1426312       2  Knight Riders    Sunrisers    10     2           1
260919   1426312       2  Knight Riders    Sunrisers    10     3           1

        is_wicket                            venue         winner  \
0               0            M Chinnaswamy Stadium  Knight Riders
1               0            M Chinnaswamy Stadium  Knight Riders
2               0            M Chinnaswamy Stadium  Knight Riders
3               0            M Chinnaswamy Stadium  Knight Riders
4               0            M Chinnaswamy Stadium  Knight Riders
...           ...                              ...            ...
260915          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260916          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260917          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260918          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260919          0  MA Chidambaram Stadium, Chepauk  Knight Riders

        cumulative_runs  overs_completed  cumulative_wickets
0                     1         0.000000                   0
1                     1         0.166667                   0
2                     2         0.333333                   0
3                     2         0.500000                   0
4                     2         0.666667                   0
...                 ...              ...                 ...
260915              110         9.666667                   2
260916              111         9.833333                   2
260917              112        10.000000                   2
260918              113        10.166667                   2
260919              114        10.333333                   2

[260920 rows x 13 columns]

In [ ]:
#Current RuN Rate

import numpy as np

merged_data['current_run_rate'] = np.where(merged_data['overs_completed']== 0,0,merged_data['cumulative_runs']/merged_data['overs_completed'])

print(merged_data)

        match_id  inning   batting_team bowling_team  over  ball  total_runs  \
0         335982       1  Knight Riders          RCB     0     1           1
1         335982       1  Knight Riders          RCB     0     2           0
2         335982       1  Knight Riders          RCB     0     3           1
3         335982       1  Knight Riders          RCB     0     4           0
4         335982       1  Knight Riders          RCB     0     5           0
...          ...     ...            ...          ...   ...   ...         ...
260915   1426312       2  Knight Riders    Sunrisers     9     5           1
260916   1426312       2  Knight Riders    Sunrisers     9     6           1
260917   1426312       2  Knight Riders    Sunrisers    10     1           1
260918   1426312       2  Knight Riders    Sunrisers    10     2           1
260919   1426312       2  Knight Riders    Sunrisers    10     3           1

        is_wicket                            venue         winner  \
0               0            M Chinnaswamy Stadium  Knight Riders
1               0            M Chinnaswamy Stadium  Knight Riders
2               0            M Chinnaswamy Stadium  Knight Riders
3               0            M Chinnaswamy Stadium  Knight Riders
4               0            M Chinnaswamy Stadium  Knight Riders
...           ...                              ...            ...
260915          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260916          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260917          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260918          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260919          0  MA Chidambaram Stadium, Chepauk  Knight Riders

        cumulative_runs  overs_completed  cumulative_wickets  current_run_rate
0                     1         0.000000                   0          0.000000
1                     1         0.166667                   0          6.000000
2                     2         0.333333                   0          6.000000
3                     2         0.500000                   0          4.000000
4                     2         0.666667                   0          3.000000
...                 ...              ...                 ...               ...
260915              110         9.666667                   2         11.379310
260916              111         9.833333                   2         11.288136
260917              112        10.000000                   2         11.200000
260918              113        10.166667                   2         11.114754
260919              114        10.333333                   2         11.032258

[260920 rows x 14 columns]

In [ ]:
merged_data.head()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,venue,winner,cumulative_runs,overs_completed,cumulative_wickets,current_run_rate
0,335982,1,Knight Riders,RCB,0,1,1,0,M Chinnaswamy Stadium,Knight Riders,1,0.000000,0,0.0
1,335982,1,Knight Riders,RCB,0,2,0,0,M Chinnaswamy Stadium,Knight Riders,1,0.166667,0,6.0
2,335982,1,Knight Riders,RCB,0,3,1,0,M Chinnaswamy Stadium,Knight Riders,2,0.333333,0,6.0
3,335982,1,Knight Riders,RCB,0,4,0,0,M Chinnaswamy Stadium,Knight Riders,2,0.500000,0,4.0
4,335982,1,Knight Riders,RCB,0,5,0,0,M Chinnaswamy Stadium,Knight Riders,2,0.666667,0,3.0

In [ ]:
# Target and Required Run Rate
#First Inning
first_inning = merged_data[merged_data['inning'] == 1]
cum_runs = first_inning['cumulative_runs'].max()
target = cum_runs + 1
print("Target:", target)

total_over = first_inning['over'].max()

print("Total Over In First Inning :",total_over)



required_run_rate = target/total_over
print("Required Run Rate",required_run_rate )
merged_data['target'] = target

Target: 288
Total Over In First Inning : 19
Required Run Rate 15.157894736842104

In [ ]:
 #Remaining Overs

total_overs = 20

merged_data['remaining_overs'] = total_overs - merged_data['overs_completed']

print(merged_data)

        match_id  inning   batting_team bowling_team  over  ball  total_runs  \
0         335982       1  Knight Riders          RCB     0     1           1
1         335982       1  Knight Riders          RCB     0     2           0
2         335982       1  Knight Riders          RCB     0     3           1
3         335982       1  Knight Riders          RCB     0     4           0
4         335982       1  Knight Riders          RCB     0     5           0
...          ...     ...            ...          ...   ...   ...         ...
260915   1426312       2  Knight Riders    Sunrisers     9     5           1
260916   1426312       2  Knight Riders    Sunrisers     9     6           1
260917   1426312       2  Knight Riders    Sunrisers    10     1           1
260918   1426312       2  Knight Riders    Sunrisers    10     2           1
260919   1426312       2  Knight Riders    Sunrisers    10     3           1

        is_wicket                            venue         winner  \
0               0            M Chinnaswamy Stadium  Knight Riders
1               0            M Chinnaswamy Stadium  Knight Riders
2               0            M Chinnaswamy Stadium  Knight Riders
3               0            M Chinnaswamy Stadium  Knight Riders
4               0            M Chinnaswamy Stadium  Knight Riders
...           ...                              ...            ...
260915          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260916          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260917          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260918          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260919          0  MA Chidambaram Stadium, Chepauk  Knight Riders

        cumulative_runs  overs_completed  cumulative_wickets  \
0                     1         0.000000                   0
1                     1         0.166667                   0
2                     2         0.333333                   0
3                     2         0.500000                   0
4                     2         0.666667                   0
...                 ...              ...                 ...
260915              110         9.666667                   2
260916              111         9.833333                   2
260917              112        10.000000                   2
260918              113        10.166667                   2
260919              114        10.333333                   2

        current_run_rate  target  remaining_overs
0               0.000000     288        20.000000
1               6.000000     288        19.833333
2               6.000000     288        19.666667
3               4.000000     288        19.500000
4               3.000000     288        19.333333
...                  ...     ...              ...
260915         11.379310     288        10.333333
260916         11.288136     288        10.166667
260917         11.200000     288        10.000000
260918         11.114754     288         9.833333
260919         11.032258     288         9.666667

[260920 rows x 16 columns]

In [ ]:
# Second Inning
second_inning = merged_data[merged_data['inning'] == 2].copy()
second_inning['required_run_rate'] = (merged_data['target'] - second_inning['cumulative_runs']) / second_inning['remaining_overs']

# Replace infinite values with 0
second_inning['required_run_rate'] = second_inning['required_run_rate'].replace([np.inf, -np.inf], 0)
second_inning['required_run_rate'] = np.where(second_inning['remaining_overs'] <= 0, 0, second_inning['required_run_rate'])

merged_data['required_run_rate'] = second_inning['required_run_rate']

print(merged_data.head)

<bound method NDFrame.head of         match_id  inning   batting_team bowling_team  over  ball  total_runs  \
0         335982       1  Knight Riders          RCB     0     1           1
1         335982       1  Knight Riders          RCB     0     2           0
2         335982       1  Knight Riders          RCB     0     3           1
3         335982       1  Knight Riders          RCB     0     4           0
4         335982       1  Knight Riders          RCB     0     5           0
...          ...     ...            ...          ...   ...   ...         ...
260915   1426312       2  Knight Riders    Sunrisers     9     5           1
260916   1426312       2  Knight Riders    Sunrisers     9     6           1
260917   1426312       2  Knight Riders    Sunrisers    10     1           1
260918   1426312       2  Knight Riders    Sunrisers    10     2           1
260919   1426312       2  Knight Riders    Sunrisers    10     3           1

        is_wicket                            venue         winner  \
0               0            M Chinnaswamy Stadium  Knight Riders
1               0            M Chinnaswamy Stadium  Knight Riders
2               0            M Chinnaswamy Stadium  Knight Riders
3               0            M Chinnaswamy Stadium  Knight Riders
4               0            M Chinnaswamy Stadium  Knight Riders
...           ...                              ...            ...
260915          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260916          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260917          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260918          0  MA Chidambaram Stadium, Chepauk  Knight Riders
260919          0  MA Chidambaram Stadium, Chepauk  Knight Riders

        cumulative_runs  overs_completed  cumulative_wickets  \
0                     1         0.000000                   0
1                     1         0.166667                   0
2                     2         0.333333                   0
3                     2         0.500000                   0
4                     2         0.666667                   0
...                 ...              ...                 ...
260915              110         9.666667                   2
260916              111         9.833333                   2
260917              112        10.000000                   2
260918              113        10.166667                   2
260919              114        10.333333                   2

        current_run_rate  target  remaining_overs  required_run_rate
0               0.000000     288        20.000000                NaN
1               6.000000     288        19.833333                NaN
2               6.000000     288        19.666667                NaN
3               4.000000     288        19.500000                NaN
4               3.000000     288        19.333333                NaN
...                  ...     ...              ...                ...
260915         11.379310     288        10.333333          17.225806
260916         11.288136     288        10.166667          17.409836
260917         11.200000     288        10.000000          17.600000
260918         11.114754     288         9.833333          17.796610
260919         11.032258     288         9.666667          18.000000

[260920 rows x 17 columns]>

In [ ]:
merged_data.head()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,venue,winner,cumulative_runs,overs_completed,cumulative_wickets,current_run_rate,target,remaining_overs,required_run_rate
0,335982,1,Knight Riders,RCB,0,1,1,0,M Chinnaswamy Stadium,Knight Riders,1,0.000000,0,0.0,288,20.000000,NaN
1,335982,1,Knight Riders,RCB,0,2,0,0,M Chinnaswamy Stadium,Knight Riders,1,0.166667,0,6.0,288,19.833333,NaN
2,335982,1,Knight Riders,RCB,0,3,1,0,M Chinnaswamy Stadium,Knight Riders,2,0.333333,0,6.0,288,19.666667,NaN
3,335982,1,Knight Riders,RCB,0,4,0,0,M Chinnaswamy Stadium,Knight Riders,2,0.500000,0,4.0,288,19.500000,NaN
4,335982,1,Knight Riders,RCB,0,5,0,0,M Chinnaswamy Stadium,Knight Riders,2,0.666667,0,3.0,288,19.333333,NaN

In [ ]:
#Drop Unnecessary columns

Merged_Data = merged_data.drop(columns=['match_id','over','ball','is_wicket','total_runs'])

print(Merged_Data.head())

   inning   batting_team bowling_team                  venue         winner  \
0       1  Knight Riders          RCB  M Chinnaswamy Stadium  Knight Riders
1       1  Knight Riders          RCB  M Chinnaswamy Stadium  Knight Riders
2       1  Knight Riders          RCB  M Chinnaswamy Stadium  Knight Riders
3       1  Knight Riders          RCB  M Chinnaswamy Stadium  Knight Riders
4       1  Knight Riders          RCB  M Chinnaswamy Stadium  Knight Riders

   cumulative_runs  overs_completed  cumulative_wickets  current_run_rate  \
0                1         0.000000                   0               0.0
1                1         0.166667                   0               6.0
2                2         0.333333                   0               6.0
3                2         0.500000                   0               4.0
4                2         0.666667                   0               3.0

   target  remaining_overs  required_run_rate
0     288        20.000000                NaN
1     288        19.833333                NaN
2     288        19.666667                NaN
3     288        19.500000                NaN
4     288        19.333333                NaN

In [ ]:
#Save Csv File
Merge
Merged_Data.to_csv("/content/drive/MyDrive/Colab Notebooks/Merged Data.csv",index=False)