In [75]:
import pandas as pd

In [76]:
matches = "C:\\Users\\Dell\\Desktop\\IPL Visualization\\matches.csv"

In [77]:
Data1_df = pd.read_csv(matches)

In [78]:
deliveries = "C:\\Users\\Dell\\Desktop\\IPL Visualization\\deliveries.csv"

In [79]:
Data2_df = pd.read_csv(deliveries)

In [80]:

print("\033[1m Matches Dataset\033[1m")
Data1_df.info()
print("\n")
print("\033[1m Deliveries Dataset\033[1m")
Data2_df.info()

 Matches Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB


 Deliveries Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [81]:
Data1_df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [82]:
#Drop columns
Data1_df.drop(columns=['match_type', 'player_of_match', 'target_runs', 'target_overs',
                'super_over', 'umpire1', 'umpire2', 'season', 'city', 'date',
                'toss_winner', 'toss_decision', 'result_margin', 'result', 'method',
                'team1', 'team2'], inplace=True)

In [83]:
#check Null Data
Data1_null = Data1_df.isnull().sum()
print(Data1_null)

id        0
venue     0
winner    5
dtype: int64

In [84]:
Data1_df.fillna({'winner':'super_over'},inplace=True)
null_counts = Data1_df.isnull().sum()
print(null_counts)

id        0
venue     0
winner    0
dtype: int64

In [85]:
Data2_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [86]:
#Drop columns
Data2_df.drop(columns=['batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs', 'extras_type', 'player_dismissed','fielder','dismissal_kind'], inplace=True)
Data2_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,1,0
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,1,0
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,0
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0,0

In [87]:
#check Null Data
Data2_null = Data2_df.isnull().sum()
print(Data2_null)

match_id        0
inning          0
batting_team    0
bowling_team    0
over            0
ball            0
total_runs      0
is_wicket       0
dtype: int64

In [88]:
team_name_mapping = {
    'Kings XI Punjab': 'Punjab Kings',
    'Delhi Daredevils': 'Delhi Capitals',
    'Chennai Super Kings': 'CSK',
    'Royal Challengers Bangalore' : 'RCB',
    'Rising Pune Supergiants' : 'Rising Pune Supergiants',
    'Kolkata Knight Riders' : 'Knight Riders',
    'Rajasthan Royals' : 'RR',
}


Data1_df['winner']=Data1_df['winner'].replace(team_name_mapping)
Data1_df.head()

       id                                       venue          winner
0  335982                       M Chinnaswamy Stadium   Knight Riders
1  335983  Punjab Cricket Association Stadium, Mohali             CSK
2  335984                            Feroz Shah Kotla  Delhi Capitals
3  335985                            Wankhede Stadium             RCB
4  335986                                Eden Gardens   Knight Riders

In [89]:
print("Data 2")
Data2_df.head()

Data 2

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,1,0
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,1,0
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,0
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0,0

In [90]:
# Merged Both Data1 and Data2
merged_data = pd.merge(Data2_df, Data1_df, left_on='match_id', right_on='id', how='left')
print("Merged Data (Deliveries Data & Matches Data)\n")
merged_data = merged_data.drop(columns=['id'])
merged_data.head()

Merged Data (Deliveries Data & Matches Data)

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,venue,winner
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,1,0,M Chinnaswamy Stadium,Knight Riders
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,0,M Chinnaswamy Stadium,Knight Riders
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,1,0,M Chinnaswamy Stadium,Knight Riders
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,0,M Chinnaswamy Stadium,Knight Riders
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0,0,M Chinnaswamy Stadium,Knight Riders

In [91]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   match_id      260920 non-null  int64
 1   inning        260920 non-null  int64
 2   batting_team  260920 non-null  object
 3   bowling_team  260920 non-null  object
 4   over          260920 non-null  int64
 5   ball          260920 non-null  int64
 6   total_runs    260920 non-null  int64
 7   is_wicket     260920 non-null  int64
 8   venue         260920 non-null  object
 9   winner        260920 non-null  object
dtypes: int64(6), object(4)
memory usage: 19.9+ MB

In [92]:
#Nul Counts Merged Data
null = merged_data.isnull().sum()
print(null)

match_id        0
inning          0
batting_team    0
bowling_team    0
over            0
ball            0
total_runs      0
is_wicket       0
venue           0
winner          0
dtype: int64

In [93]:
# Cumulative Runs
merged_data["cumulative_runs"] = merged_data.groupby(['match_id','inning'])['total_runs'].cumsum()
print(merged_data)

        match_id  inning           batting_team                 bowling_team  \
0         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
1         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
2         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
3         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
4         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
...          ...     ...                    ...                          ...
260915   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260916   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260917   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260918   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260919   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad

        over  ball  total_runs  is_wicket  \
0          0     1           1          0
1          0     2           0          0
2          0     3           1          0
3          0     4           0          0
4          0     5           0          0
...      ...   ...         ...        ...
260915     9     5           1          0
260916     9     6           1          0
260917    10     1           1          0
260918    10     2           1          0
260919    10     3           1          0

                                           venue         winner  \
0                          M Chinnaswamy Stadium  Knight Riders
1                          M Chinnaswamy Stadium  Knight Riders
2                          M Chinnaswamy Stadium  Knight Riders
3                          M Chinnaswamy Stadium  Knight Riders
4                          M Chinnaswamy Stadium  Knight Riders
...                                          ...            ...
260915  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260916  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260917  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260918  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260919  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders

        cumulative_runs
0                     1
1                     1
2                     2
3                     2
4                     2
...                 ...
260915              110
260916              111
260917              112
260918              113
260919              114

[260920 rows x 11 columns]

In [94]:
# Overs Completed 

merged_data["overs_completed"] =  merged_data['over'] + (merged_data['ball'] - 1) / 6

print(merged_data)

        match_id  inning           batting_team                 bowling_team  \
0         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
1         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
2         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
3         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
4         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
...          ...     ...                    ...                          ...
260915   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260916   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260917   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260918   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260919   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad

        over  ball  total_runs  is_wicket  \
0          0     1           1          0
1          0     2           0          0
2          0     3           1          0
3          0     4           0          0
4          0     5           0          0
...      ...   ...         ...        ...
260915     9     5           1          0
260916     9     6           1          0
260917    10     1           1          0
260918    10     2           1          0
260919    10     3           1          0

                                           venue         winner  \
0                          M Chinnaswamy Stadium  Knight Riders
1                          M Chinnaswamy Stadium  Knight Riders
2                          M Chinnaswamy Stadium  Knight Riders
3                          M Chinnaswamy Stadium  Knight Riders
4                          M Chinnaswamy Stadium  Knight Riders
...                                          ...            ...
260915  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260916  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260917  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260918  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260919  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders

        cumulative_runs  overs_completed
0                     1         0.000000
1                     1         0.166667
2                     2         0.333333
3                     2         0.500000
4                     2         0.666667
...                 ...              ...
260915              110         9.666667
260916              111         9.833333
260917              112        10.000000
260918              113        10.166667
260919              114        10.333333

[260920 rows x 12 columns]

In [95]:
#Cumulative Wickets

merged_data["cumulative_wickets"] = merged_data.groupby(['match_id','inning'])['is_wicket'].cumsum()
print(merged_data)

        match_id  inning           batting_team                 bowling_team  \
0         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
1         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
2         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
3         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
4         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
...          ...     ...                    ...                          ...
260915   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260916   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260917   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260918   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260919   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad

        over  ball  total_runs  is_wicket  \
0          0     1           1          0
1          0     2           0          0
2          0     3           1          0
3          0     4           0          0
4          0     5           0          0
...      ...   ...         ...        ...
260915     9     5           1          0
260916     9     6           1          0
260917    10     1           1          0
260918    10     2           1          0
260919    10     3           1          0

                                           venue         winner  \
0                          M Chinnaswamy Stadium  Knight Riders
1                          M Chinnaswamy Stadium  Knight Riders
2                          M Chinnaswamy Stadium  Knight Riders
3                          M Chinnaswamy Stadium  Knight Riders
4                          M Chinnaswamy Stadium  Knight Riders
...                                          ...            ...
260915  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260916  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260917  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260918  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260919  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders

        cumulative_runs  overs_completed  cumulative_wickets
0                     1         0.000000                   0
1                     1         0.166667                   0
2                     2         0.333333                   0
3                     2         0.500000                   0
4                     2         0.666667                   0
...                 ...              ...                 ...
260915              110         9.666667                   2
260916              111         9.833333                   2
260917              112        10.000000                   2
260918              113        10.166667                   2
260919              114        10.333333                   2

[260920 rows x 13 columns]

In [96]:
#Current RuN Rate

import numpy as np

merged_data['current_run_rate'] = np.where(merged_data['overs_completed']== 0,0,merged_data['cumulative_runs']/merged_data['overs_completed'])

print(merged_data)

        match_id  inning           batting_team                 bowling_team  \
0         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
1         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
2         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
3         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
4         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
...          ...     ...                    ...                          ...
260915   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260916   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260917   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260918   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260919   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad

        over  ball  total_runs  is_wicket  \
0          0     1           1          0
1          0     2           0          0
2          0     3           1          0
3          0     4           0          0
4          0     5           0          0
...      ...   ...         ...        ...
260915     9     5           1          0
260916     9     6           1          0
260917    10     1           1          0
260918    10     2           1          0
260919    10     3           1          0

                                           venue         winner  \
0                          M Chinnaswamy Stadium  Knight Riders
1                          M Chinnaswamy Stadium  Knight Riders
2                          M Chinnaswamy Stadium  Knight Riders
3                          M Chinnaswamy Stadium  Knight Riders
4                          M Chinnaswamy Stadium  Knight Riders
...                                          ...            ...
260915  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260916  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260917  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260918  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260919  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders

        cumulative_runs  overs_completed  cumulative_wickets  current_run_rate
0                     1         0.000000                   0          0.000000
1                     1         0.166667                   0          6.000000
2                     2         0.333333                   0          6.000000
3                     2         0.500000                   0          4.000000
4                     2         0.666667                   0          3.000000
...                 ...              ...                 ...               ...
260915              110         9.666667                   2         11.379310
260916              111         9.833333                   2         11.288136
260917              112        10.000000                   2         11.200000
260918              113        10.166667                   2         11.114754
260919              114        10.333333                   2         11.032258

[260920 rows x 14 columns]

In [97]:
merged_data.head()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,venue,winner,cumulative_runs,overs_completed,cumulative_wickets,current_run_rate
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,1,0,M Chinnaswamy Stadium,Knight Riders,1,0.000000,0,0.0
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,0,M Chinnaswamy Stadium,Knight Riders,1,0.166667,0,6.0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,1,0,M Chinnaswamy Stadium,Knight Riders,2,0.333333,0,6.0
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,0,M Chinnaswamy Stadium,Knight Riders,2,0.500000,0,4.0
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0,0,M Chinnaswamy Stadium,Knight Riders,2,0.666667,0,3.0

In [98]:
# Target and Required Run Rate 
#First Inning
first_inning = merged_data[merged_data['inning'] == 1]
cum_runs = first_inning['cumulative_runs'].max()
target = cum_runs + 1
print("Target:", target)

total_over = first_inning['over'].max()

print("Total Over In First Inning :",total_over)



required_run_rate = target/total_over
print("Required Run Rate",required_run_rate )
merged_data['target'] = target

Target: 288
Total Over In First Inning : 19
Required Run Rate 15.157894736842104

In [99]:
 #Remaining Overs

total_overs = 20

merged_data['remaining_overs'] = total_overs - merged_data['overs_completed']

print(merged_data)

        match_id  inning           batting_team                 bowling_team  \
0         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
1         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
2         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
3         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
4         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
...          ...     ...                    ...                          ...
260915   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260916   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260917   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260918   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260919   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad

        over  ball  total_runs  is_wicket  \
0          0     1           1          0
1          0     2           0          0
2          0     3           1          0
3          0     4           0          0
4          0     5           0          0
...      ...   ...         ...        ...
260915     9     5           1          0
260916     9     6           1          0
260917    10     1           1          0
260918    10     2           1          0
260919    10     3           1          0

                                           venue         winner  \
0                          M Chinnaswamy Stadium  Knight Riders
1                          M Chinnaswamy Stadium  Knight Riders
2                          M Chinnaswamy Stadium  Knight Riders
3                          M Chinnaswamy Stadium  Knight Riders
4                          M Chinnaswamy Stadium  Knight Riders
...                                          ...            ...
260915  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260916  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260917  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260918  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260919  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders

        cumulative_runs  overs_completed  cumulative_wickets  \
0                     1         0.000000                   0
1                     1         0.166667                   0
2                     2         0.333333                   0
3                     2         0.500000                   0
4                     2         0.666667                   0
...                 ...              ...                 ...
260915              110         9.666667                   2
260916              111         9.833333                   2
260917              112        10.000000                   2
260918              113        10.166667                   2
260919              114        10.333333                   2

        current_run_rate  target  remaining_overs
0               0.000000     288        20.000000
1               6.000000     288        19.833333
2               6.000000     288        19.666667
3               4.000000     288        19.500000
4               3.000000     288        19.333333
...                  ...     ...              ...
260915         11.379310     288        10.333333
260916         11.288136     288        10.166667
260917         11.200000     288        10.000000
260918         11.114754     288         9.833333
260919         11.032258     288         9.666667

[260920 rows x 16 columns]

In [100]:
# Second Inning
second_inning = merged_data[merged_data['inning'] == 2].copy()
second_inning['required_run_rate'] = (merged_data['target'] - second_inning['cumulative_runs']) / second_inning['remaining_overs']

# Replace infinite values with 0
second_inning['required_run_rate'] = second_inning['required_run_rate'].replace([np.inf, -np.inf], 0)
second_inning['required_run_rate'] = np.where(second_inning['remaining_overs'] <= 0, 0, second_inning['required_run_rate'])

merged_data['required_run_rate'] = second_inning['required_run_rate'] 

print(merged_data.head)

<bound method NDFrame.head of         match_id  inning           batting_team                 bowling_team  \
0         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
1         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
2         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
3         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
4         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
...          ...     ...                    ...                          ...
260915   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260916   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260917   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260918   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260919   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad

        over  ball  total_runs  is_wicket  \
0          0     1           1          0
1          0     2           0          0
2          0     3           1          0
3          0     4           0          0
4          0     5           0          0
...      ...   ...         ...        ...
260915     9     5           1          0
260916     9     6           1          0
260917    10     1           1          0
260918    10     2           1          0
260919    10     3           1          0

                                           venue         winner  \
0                          M Chinnaswamy Stadium  Knight Riders
1                          M Chinnaswamy Stadium  Knight Riders
2                          M Chinnaswamy Stadium  Knight Riders
3                          M Chinnaswamy Stadium  Knight Riders
4                          M Chinnaswamy Stadium  Knight Riders
...                                          ...            ...
260915  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260916  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260917  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260918  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders
260919  MA Chidambaram Stadium, Chepauk, Chennai  Knight Riders

        cumulative_runs  overs_completed  cumulative_wickets  \
0                     1         0.000000                   0
1                     1         0.166667                   0
2                     2         0.333333                   0
3                     2         0.500000                   0
4                     2         0.666667                   0
...                 ...              ...                 ...
260915              110         9.666667                   2
260916              111         9.833333                   2
260917              112        10.000000                   2
260918              113        10.166667                   2
260919              114        10.333333                   2

        current_run_rate  target  remaining_overs  required_run_rate
0               0.000000     288        20.000000                NaN
1               6.000000     288        19.833333                NaN
2               6.000000     288        19.666667                NaN
3               4.000000     288        19.500000                NaN
4               3.000000     288        19.333333                NaN
...                  ...     ...              ...                ...
260915         11.379310     288        10.333333          17.225806
260916         11.288136     288        10.166667          17.409836
260917         11.200000     288        10.000000          17.600000
260918         11.114754     288         9.833333          17.796610
260919         11.032258     288         9.666667          18.000000

[260920 rows x 17 columns]>

In [101]:
merged_data.head()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,venue,winner,cumulative_runs,overs_completed,cumulative_wickets,current_run_rate,target,remaining_overs,required_run_rate
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,1,0,M Chinnaswamy Stadium,Knight Riders,1,0.000000,0,0.0,288,20.000000,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,0,M Chinnaswamy Stadium,Knight Riders,1,0.166667,0,6.0,288,19.833333,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,1,0,M Chinnaswamy Stadium,Knight Riders,2,0.333333,0,6.0,288,19.666667,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,0,M Chinnaswamy Stadium,Knight Riders,2,0.500000,0,4.0,288,19.500000,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0,0,M Chinnaswamy Stadium,Knight Riders,2,0.666667,0,3.0,288,19.333333,NaN

In [102]:
#Drop Unnecessary columns

Merged_Data = merged_data.drop(columns=['match_id','over','ball','is_wicket','total_runs'])

print(Merged_Data.head())

   inning           batting_team                 bowling_team  \
0       1  Kolkata Knight Riders  Royal Challengers Bangalore
1       1  Kolkata Knight Riders  Royal Challengers Bangalore
2       1  Kolkata Knight Riders  Royal Challengers Bangalore
3       1  Kolkata Knight Riders  Royal Challengers Bangalore
4       1  Kolkata Knight Riders  Royal Challengers Bangalore

                   venue         winner  cumulative_runs  overs_completed  \
0  M Chinnaswamy Stadium  Knight Riders                1         0.000000
1  M Chinnaswamy Stadium  Knight Riders                1         0.166667
2  M Chinnaswamy Stadium  Knight Riders                2         0.333333
3  M Chinnaswamy Stadium  Knight Riders                2         0.500000
4  M Chinnaswamy Stadium  Knight Riders                2         0.666667

   cumulative_wickets  current_run_rate  target  remaining_overs  \
0                   0               0.0     288        20.000000
1                   0               6.0     288        19.833333
2                   0               6.0     288        19.666667
3                   0               4.0     288        19.500000
4                   0               3.0     288        19.333333

   required_run_rate
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN

In [103]:
Merged_Data['win'] = np.where(Merged_Data['batting_team'] == Merged_Data['winner'],1,0)
second_inning = Merged_Data[Merged_Data['inning']==2]
print(second_inning.head())

     inning                 batting_team           bowling_team  \
124       2  Royal Challengers Bangalore  Kolkata Knight Riders
125       2  Royal Challengers Bangalore  Kolkata Knight Riders
126       2  Royal Challengers Bangalore  Kolkata Knight Riders
127       2  Royal Challengers Bangalore  Kolkata Knight Riders
128       2  Royal Challengers Bangalore  Kolkata Knight Riders

                     venue         winner  cumulative_runs  overs_completed  \
124  M Chinnaswamy Stadium  Knight Riders                1         0.000000
125  M Chinnaswamy Stadium  Knight Riders                2         0.166667
126  M Chinnaswamy Stadium  Knight Riders                2         0.333333
127  M Chinnaswamy Stadium  Knight Riders                3         0.500000
128  M Chinnaswamy Stadium  Knight Riders                4         0.666667

     cumulative_wickets  current_run_rate  target  remaining_overs  \
124                   0               0.0     288        20.000000
125                   0              12.0     288        19.833333
126                   0               6.0     288        19.666667
127                   0               6.0     288        19.500000
128                   0               6.0     288        19.333333

     required_run_rate  win
124          14.350000    0
125          14.420168    0
126          14.542373    0
127          14.615385    0
128          14.689655    0

In [104]:
#Drop Winner Column 
Merged_Data = Merged_Data.drop(columns=['winner'])
print(Merged_Data)

        inning           batting_team                 bowling_team  \
0            1  Kolkata Knight Riders  Royal Challengers Bangalore
1            1  Kolkata Knight Riders  Royal Challengers Bangalore
2            1  Kolkata Knight Riders  Royal Challengers Bangalore
3            1  Kolkata Knight Riders  Royal Challengers Bangalore
4            1  Kolkata Knight Riders  Royal Challengers Bangalore
...        ...                    ...                          ...
260915       2  Kolkata Knight Riders          Sunrisers Hyderabad
260916       2  Kolkata Knight Riders          Sunrisers Hyderabad
260917       2  Kolkata Knight Riders          Sunrisers Hyderabad
260918       2  Kolkata Knight Riders          Sunrisers Hyderabad
260919       2  Kolkata Knight Riders          Sunrisers Hyderabad

                                           venue  cumulative_runs  \
0                          M Chinnaswamy Stadium                1
1                          M Chinnaswamy Stadium                1
2                          M Chinnaswamy Stadium                2
3                          M Chinnaswamy Stadium                2
4                          M Chinnaswamy Stadium                2
...                                          ...              ...
260915  MA Chidambaram Stadium, Chepauk, Chennai              110
260916  MA Chidambaram Stadium, Chepauk, Chennai              111
260917  MA Chidambaram Stadium, Chepauk, Chennai              112
260918  MA Chidambaram Stadium, Chepauk, Chennai              113
260919  MA Chidambaram Stadium, Chepauk, Chennai              114

        overs_completed  cumulative_wickets  current_run_rate  target  \
0              0.000000                   0          0.000000     288
1              0.166667                   0          6.000000     288
2              0.333333                   0          6.000000     288
3              0.500000                   0          4.000000     288
4              0.666667                   0          3.000000     288
...                 ...                 ...               ...     ...
260915         9.666667                   2         11.379310     288
260916         9.833333                   2         11.288136     288
260917        10.000000                   2         11.200000     288
260918        10.166667                   2         11.114754     288
260919        10.333333                   2         11.032258     288

        remaining_overs  required_run_rate  win
0             20.000000                NaN    0
1             19.833333                NaN    0
2             19.666667                NaN    0
3             19.500000                NaN    0
4             19.333333                NaN    0
...                 ...                ...  ...
260915        10.333333          17.225806    0
260916        10.166667          17.409836    0
260917        10.000000          17.600000    0
260918         9.833333          17.796610    0
260919         9.666667          18.000000    0

[260920 rows x 12 columns]

In [106]:
Merged_Data.to_csv("C:\\Users\\Dell\\Desktop\\IPL Visualization\\Merged Data.csv",index=False)

In [107]:
Null_Counts = Merged_Data.isnull().sum()
print(Null_Counts)

inning                     0
batting_team               0
bowling_team               0
venue                      0
cumulative_runs            0
overs_completed            0
cumulative_wickets         0
current_run_rate           0
target                     0
remaining_overs            0
required_run_rate     135179
win                        0
dtype: int64