In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df1=pd.read_csv('deliveries.csv')

In [3]:
df1.shape

(260920, 17)

In [4]:
df2=pd.read_csv('matches.csv')

In [5]:
df2.shape

(1095, 20)

In [6]:
df1.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [7]:
df1.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [8]:
df1['extras_type'].fillna('no extras', inplace=True)
df1['player_dismissed'].fillna('not dismissed', inplace=True)
df1['dismissal_kind'].fillna('no dismissal', inplace=True)
df1['fielder'].fillna('no fielding', inplace=True)

In [9]:
df2.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [10]:
df2.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [11]:
df2['winner'].fillna('no result', inplace=True)
df2['player_of_match'].fillna('no one', inplace=True)
df2['result_margin'].fillna(0, inplace=True)

In [12]:
df1.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
260915    False
260916    False
260917    False
260918    False
260919    False
Length: 260920, dtype: bool

In [13]:
df2.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1090    False
1091    False
1092    False
1093    False
1094    False
Length: 1095, dtype: bool

In [15]:
selected_columns_df1 = ['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball', 'total_runs', 'is_wicket']
selected_columns_df2 = ['id', 'date', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin']

merged_df = pd.merge(df1[selected_columns_df1], df2[selected_columns_df2], 
                     left_on='match_id', right_on='id')
print(merged_df)

        match_id  inning           batting_team                 bowling_team  \
0         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
1         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
2         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
3         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
4         335982       1  Kolkata Knight Riders  Royal Challengers Bangalore
...          ...     ...                    ...                          ...
260915   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260916   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260917   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260918   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad
260919   1426312       2  Kolkata Knight Riders          Sunrisers Hyderabad

        over  ball  total_runs  is_wicket       id        date  \
0          0     1           1          0   335982  2008-04-18
1          0     2           0          0   335982  2008-04-18
2          0     3           1          0   335982  2008-04-18
3          0     4           0          0   335982  2008-04-18
4          0     5           0          0   335982  2008-04-18
...      ...   ...         ...        ...      ...         ...
260915     9     5           1          0  1426312  2024-05-26
260916     9     6           1          0  1426312  2024-05-26
260917    10     1           1          0  1426312  2024-05-26
260918    10     2           1          0  1426312  2024-05-26
260919    10     3           1          0  1426312  2024-05-26

                              team1                  team2  \
0       Royal Challengers Bangalore  Kolkata Knight Riders
1       Royal Challengers Bangalore  Kolkata Knight Riders
2       Royal Challengers Bangalore  Kolkata Knight Riders
3       Royal Challengers Bangalore  Kolkata Knight Riders
4       Royal Challengers Bangalore  Kolkata Knight Riders
...                             ...                    ...
260915          Sunrisers Hyderabad  Kolkata Knight Riders
260916          Sunrisers Hyderabad  Kolkata Knight Riders
260917          Sunrisers Hyderabad  Kolkata Knight Riders
260918          Sunrisers Hyderabad  Kolkata Knight Riders
260919          Sunrisers Hyderabad  Kolkata Knight Riders

                        toss_winner toss_decision                 winner  \
0       Royal Challengers Bangalore         field  Kolkata Knight Riders
1       Royal Challengers Bangalore         field  Kolkata Knight Riders
2       Royal Challengers Bangalore         field  Kolkata Knight Riders
3       Royal Challengers Bangalore         field  Kolkata Knight Riders
4       Royal Challengers Bangalore         field  Kolkata Knight Riders
...                             ...           ...                    ...
260915          Sunrisers Hyderabad           bat  Kolkata Knight Riders
260916          Sunrisers Hyderabad           bat  Kolkata Knight Riders
260917          Sunrisers Hyderabad           bat  Kolkata Knight Riders
260918          Sunrisers Hyderabad           bat  Kolkata Knight Riders
260919          Sunrisers Hyderabad           bat  Kolkata Knight Riders

         result  result_margin
0          runs          140.0
1          runs          140.0
2          runs          140.0
3          runs          140.0
4          runs          140.0
...         ...            ...
260915  wickets            8.0
260916  wickets            8.0
260917  wickets            8.0
260918  wickets            8.0
260919  wickets            8.0

[260920 rows x 17 columns]

In [16]:
merged_df.isnull().sum()

match_id         0
inning           0
batting_team     0
bowling_team     0
over             0
ball             0
total_runs       0
is_wicket        0
id               0
date             0
team1            0
team2            0
toss_winner      0
toss_decision    0
winner           0
result           0
result_margin    0
dtype: int64

In [23]:
merged_df['Cumulative_runs']=merged_df.groupby(["match_id","inning"])['total_runs'].cumsum()
print("\Cumulative runs")
print(merged_df[['match_id','inning','Cumulative_runs']].head())

\Cumulative runs
   match_id  inning  Cumulative_runs
0    335982       1                1
1    335982       1                1
2    335982       1                2
3    335982       1                2
4    335982       1                2

In [27]:
merged_df['cumulative_wickets'] = merged_df.groupby(['match_id', 'inning'])['is_wicket'].cumsum()
print("\Cumulative Wickets")
print(merged_df[['match_id', 'inning', 'cumulative_wickets']].head())

\Cumulative Wickets
   match_id  inning  cumulative_wickets
0    335982       1                   0
1    335982       1                   0
2    335982       1                   0
3    335982       1                   0
4    335982       1                   0

In [31]:
merged_df['cumulative_runs'] = merged_df.groupby(['match_id', 'inning'])['total_runs'].cumsum()
merged_df['overs_faced'] = merged_df['over'] + (merged_df['ball'] - 1) / 6
merged_df['overs_faced'].replace(0, 0.1, inplace=True) 
merged_df['current_run_rate'] = merged_df['cumulative_runs'] / merged_df['overs_faced']
print(merged_df[['match_id', 'inning', 'over', 'ball', 'total_runs', 'cumulative_runs', 'overs_faced', 'current_run_rate']].head())

   match_id  inning  over  ball  total_runs  cumulative_runs  overs_faced  \
0    335982       1     0     1           1                1     0.100000
1    335982       1     0     2           0                1     0.166667
2    335982       1     0     3           1                2     0.333333
3    335982       1     0     4           0                2     0.500000
4    335982       1     0     5           0                2     0.666667

   current_run_rate
0              10.0
1               6.0
2               6.0
3               4.0
4               3.0

In [35]:
merged_df['cumulative_runs'] = merged_df.groupby(['match_id', 'inning'])['total_runs'].cumsum()
merged_df['overs_faced'] = merged_df['over'] + (merged_df['ball'] - 1) / 6
merged_df['overs_faced'].replace(0, 0.1, inplace=True) 
merged_df['overs_completed'] = merged_df['over'] + merged_df['ball'] / 6
print(merged_df[['match_id', 'inning', 'over', 'ball', 'total_runs', 'overs_faced', 'overs_completed']])

        match_id  inning  over  ball  total_runs  overs_faced  overs_completed
0         335982       1     0     1           1     0.100000         0.166667
1         335982       1     0     2           0     0.166667         0.333333
2         335982       1     0     3           1     0.333333         0.500000
3         335982       1     0     4           0     0.500000         0.666667
4         335982       1     0     5           0     0.666667         0.833333
...          ...     ...   ...   ...         ...          ...              ...
260915   1426312       2     9     5           1     9.666667         9.833333
260916   1426312       2     9     6           1     9.833333        10.000000
260917   1426312       2    10     1           1    10.000000        10.166667
260918   1426312       2    10     2           1    10.166667        10.333333
260919   1426312       2    10     3           1    10.333333        10.500000

[260920 rows x 7 columns]

In [38]:
target_score = merged_df[merged_df['inning'] == 1]['total_runs'].sum() + 1
remaining_runs = target_score - merged_df['cumulative_runs']
remaining_overs = 20 - merged_df['overs_completed']  # Assuming a 20-over match
merged_df['required_run_rate'] = remaining_runs / remaining_overs
print(merged_df[['match_id', 'inning', 'over', 'ball', 'total_runs', 'cumulative_runs', 'overs_faced', 'overs_completed', 'required_run_rate']])

        match_id  inning  over  ball  total_runs  cumulative_runs  \
0         335982       1     0     1           1                1
1         335982       1     0     2           0                1
2         335982       1     0     3           1                2
3         335982       1     0     4           0                2
4         335982       1     0     5           0                2
...          ...     ...   ...   ...         ...              ...
260915   1426312       2     9     5           1              110
260916   1426312       2     9     6           1              111
260917   1426312       2    10     1           1              112
260918   1426312       2    10     2           1              113
260919   1426312       2    10     3           1              114

        overs_faced  overs_completed  required_run_rate
0          0.100000         0.166667        9139.865546
1          0.166667         0.333333        9217.322034
2          0.333333         0.500000        9296.051282
3          0.500000         0.666667        9376.189655
4          0.666667         0.833333        9457.721739
...             ...              ...                ...
260915     9.666667         9.833333       17819.508197
260916     9.833333        10.000000       18116.400000
260917    10.000000        10.166667       18423.355932
260918    10.166667        10.333333       18740.896552
260919    10.333333        10.500000       19069.578947

[260920 rows x 9 columns]