importing libraries

In [1]:
import pandas as pd

loading and reading the data

In [2]:
matches=pd.read_csv(r"matches.csv")
matches

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [3]:
deliveries=pd.read_csv(r"deliveries.csv")
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

info of matches and deliveries

In [4]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [5]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

checking for null values

In [6]:
matches.isnull().any()

id                 False
season             False
city                True
date               False
match_type         False
player_of_match     True
venue              False
team1              False
team2              False
toss_winner        False
toss_decision      False
winner              True
result             False
result_margin       True
target_runs         True
target_overs        True
super_over         False
method              True
umpire1            False
umpire2            False
dtype: bool

In [7]:
deliveries.isnull().any()

match_id            False
inning              False
batting_team        False
bowling_team        False
over                False
ball                False
batter              False
bowler              False
non_striker         False
batsman_runs        False
extra_runs          False
total_runs          False
extras_type          True
is_wicket           False
player_dismissed     True
dismissal_kind       True
fielder              True
dtype: bool

sum of null values in all columns

In [8]:
matches.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [9]:
deliveries.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

matches dataset

dropping unnecessary columns in matches

In [10]:
drop_columns_in_matches=['match_type','player_of_match','target_runs','target_overs','super_over','method','umpire1','umpire2']
matches.drop(columns=drop_columns_in_matches,inplace=True,errors='ignore')

columns present in matches dataset after dropping unnecessary columns

In [11]:
print(matches.columns)

Index(['id', 'season', 'city', 'date', 'venue', 'team1', 'team2',
       'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin'],
      dtype='object')

renaming team columns

In [12]:
rename_team = {
    'team1':'home_team',
    'team2':'away_team'
}
matches.rename(columns=rename_team,inplace=True)

after renaming teams

In [13]:
print(matches.columns)

Index(['id', 'season', 'city', 'date', 'venue', 'home_team', 'away_team',
       'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin'],
      dtype='object')

mapping venue to cities for missing values

In [14]:
venue_city = {
    'Dubai International Cricket Stadium': 'Dubai',
    'Sharjah Cricket Stadium': 'Sharjah',
    'Sheikh Zayed Stadium': 'Abu Dhabi'
}

matches['city'] = matches.apply(lambda x: venue_city.get(x['venue'], x['city']), axis=1)
matches['city'].fillna('Unknown', inplace=True)

filling missing values of winner and result margin

In [15]:
matches['winner'].fillna("no reasult",inplace=True)

In [16]:
matches['result_margin'].fillna(0,inplace=True)

standarlizing team name in mathces

In [17]:
team_name = {
    'Kings XI Punjab': 'Punjab Kings',
    'Delhi Daredevils': 'Delhi Capitals',
    'Deccan Chargers': 'Sunrisers Hyderabad'
}

matches['home_team'] = matches['home_team'].replace(team_name)
matches['away_teeam'] = matches['away_team'].replace(team_name)
matches['winner'] = matches['winner'].replace(team_name)
matches['toss_winner'] = matches['toss_winner'].replace(team_name)

deliveries dataset

only the columns whice are useful are taken from deliveries dataset

In [18]:
deliveries = deliveries[['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball', 'total_runs', 'is_wicket']]

standardizing team name in deliveries

In [19]:
deliveries = deliveries.copy()
deliveries['batting_team'] = deliveries['batting_team'].replace(team_name)
deliveries['bowling_team'] = deliveries['bowling_team'].replace(team_name)

calculating cumilative runs,wickets

In [20]:
deliveries['cumulative runs'] = deliveries.groupby(['match_id', 'inning'])['total_runs'].cumsum()
deliveries['cumumulative wickets'] = deliveries.groupby(['match_id', 'inning'])['is_wicket'].cumsum()

overs completed

In [21]:
deliveries['over_completed']= deliveries['over']+(deliveries['ball']-1)/6

current run rate

In [22]:
deliveries['current run rate'] = deliveries['cumulative runs']/deliveries['over_completed']
deliveries['current run rate'].fillna(0,inplace=True)

target and run rate for second innings

In [23]:
first_innings_scores = deliveries[deliveries['inning'] == 1].groupby('match_id')['cumulative runs'].max().reset_index()
first_innings_scores.rename(columns={'cumulative runs': 'target_score'}, inplace=True)

In [24]:
first_innings_scores['target'] = first_innings_scores['target_score'] + 1

merging target in to deliveries

In [25]:
deliveries = deliveries.merge(first_innings_scores[['match_id', 'target']], on='match_id', how='left')

run rate for second innings

In [26]:
deliveries['remaining_overs'] = 20 - deliveries['over_completed']
deliveries['required_run_rate'] = (deliveries['target'] - deliveries['cumulative runs']) / deliveries['remaining_overs']
deliveries['required_run_rate'].fillna(0, inplace=True)

merge matches and deliveries data

In [27]:
merged = deliveries.merge(matches, left_on='match_id', right_on='id', how='left')
merged.drop(columns=['id'], inplace=True)

In [28]:
merged

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,cumulative runs,cumumulative wickets,...,date,venue,home_team,away_team,toss_winner,toss_decision,winner,result,result_margin,away_teeam
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,1,0,1,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,0,1,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,1,0,2,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,0,2,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0,0,2,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,1,0,110,2,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,Kolkata Knight Riders
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,1,0,111,2,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,Kolkata Knight Riders
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,1,0,112,2,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,Kolkata Knight Riders
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,1,0,113,2,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,Kolkata Knight Riders
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,1,0,114,2,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,Kolkata Knight Riders

In [29]:
merged.head()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,cumulative runs,cumumulative wickets,...,date,venue,home_team,away_team,toss_winner,toss_decision,winner,result,result_margin,away_teeam
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,1,0,1,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,0,1,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,1,0,2,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,0,2,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0,0,2,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders

In [30]:
merged.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'total_runs', 'is_wicket', 'cumulative runs', 'cumumulative wickets',
       'over_completed', 'current run rate', 'target', 'remaining_overs',
       'required_run_rate', 'season', 'city', 'date', 'venue', 'home_team',
       'away_team', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'away_teeam'],
      dtype='object')

In [31]:
merged.isnull()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,cumulative runs,cumumulative wickets,...,date,venue,home_team,away_team,toss_winner,toss_decision,winner,result,result_margin,away_teeam
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
260916,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
260917,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
260918,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
260919,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [32]:
merged.isnull().any()

match_id                False
inning                  False
batting_team            False
bowling_team            False
over                    False
ball                    False
total_runs              False
is_wicket               False
cumulative runs         False
cumumulative wickets    False
over_completed          False
current run rate        False
target                  False
remaining_overs         False
required_run_rate       False
season                  False
city                    False
date                    False
venue                   False
home_team               False
away_team               False
toss_winner             False
toss_decision           False
winner                  False
result                  False
result_margin           False
away_teeam              False
dtype: bool

In [33]:
merged.isnull().sum()

match_id                0
inning                  0
batting_team            0
bowling_team            0
over                    0
ball                    0
total_runs              0
is_wicket               0
cumulative runs         0
cumumulative wickets    0
over_completed          0
current run rate        0
target                  0
remaining_overs         0
required_run_rate       0
season                  0
city                    0
date                    0
venue                   0
home_team               0
away_team               0
toss_winner             0
toss_decision           0
winner                  0
result                  0
result_margin           0
away_teeam              0
dtype: int64

no null values in merged data

In [34]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 260920 entries, 0 to 260919
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   match_id              260920 non-null  int64
 1   inning                260920 non-null  int64
 2   batting_team          260920 non-null  object
 3   bowling_team          260920 non-null  object
 4   over                  260920 non-null  int64
 5   ball                  260920 non-null  int64
 6   total_runs            260920 non-null  int64
 7   is_wicket             260920 non-null  int64
 8   cumulative runs       260920 non-null  int64
 9   cumumulative wickets  260920 non-null  int64
 10  over_completed        260920 non-null  float64
 11  current run rate      260920 non-null  float64
 12  target                260920 non-null  int64
 13  remaining_overs       260920 non-null  float64
 14  required_run_rate     260920 non-null  float64
 15  season                260920 non-null  object
 16  city                  260920 non-null  object
 17  date                  260920 non-null  object
 18  venue                 260920 non-null  object
 19  home_team             260920 non-null  object
 20  away_team             260920 non-null  object
 21  toss_winner           260920 non-null  object
 22  toss_decision         260920 non-null  object
 23  winner                260920 non-null  object
 24  result                260920 non-null  object
 25  result_margin         260920 non-null  float64
 26  away_teeam            260920 non-null  object
dtypes: float64(5), int64(9), object(13)
memory usage: 55.7+ MB